# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MissionGeneratorUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1088, 656)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scenario_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.scenario_comboBox.setGeometry(QtCore.QRect(140, 30, 411, 31))
        self.scenario_comboBox.setObjectName("scenario_comboBox")
        self.scenario_label = QtWidgets.QLabel(self.centralwidget)
        self.scenario_label.setGeometry(QtCore.QRect(20, 30, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.scenario_label.setFont(font)
        self.scenario_label.setObjectName("scenario_label")
        self.generateButton = QtWidgets.QPushButton(self.centralwidget)
        self.generateButton.setGeometry(QtCore.QRect(910, 550, 141, 41))
        self.generateButton.setStyleSheet("background-color: white;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.generateButton.setObjectName("generateButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-30, 200, 1111, 501))
        self.label.setStyleSheet("border-radius: 5")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("assets/background.PNG"))
        self.label.setObjectName("label")
        self.description_textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.description_textBrowser.setGeometry(QtCore.QRect(770, 30, 271, 171))
        self.description_textBrowser.setStyleSheet("border-radius: 5px;")
        self.description_textBrowser.setObjectName("description_textBrowser")
        self.blueforces_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.blueforces_comboBox.setGeometry(QtCore.QRect(770, 240, 291, 31))
        self.blueforces_comboBox.setObjectName("blueforces_comboBox")
        self.scenario_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.scenario_label_2.setGeometry(QtCore.QRect(600, 240, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.scenario_label_2.setFont(font)
        self.scenario_label_2.setObjectName("scenario_label_2")
        self.scenario_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.scenario_label_3.setGeometry(QtCore.QRect(600, 300, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.scenario_label_3.setFont(font)
        self.scenario_label_3.setObjectName("scenario_label_3")
        self.redforces_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.redforces_comboBox.setGeometry(QtCore.QRect(770, 300, 291, 31))
        self.redforces_comboBox.setObjectName("redforces_comboBox")
        self.players_spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.players_spinBox.setGeometry(QtCore.QRect(960, 380, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.players_spinBox.setFont(font)
        self.players_spinBox.setMinimum(1)
        self.players_spinBox.setMaximum(10)
        self.players_spinBox.setObjectName("players_spinBox")
        self.scenario_label_4 = QtWidgets.QLabel(self.centralwidget)
        self.scenario_label_4.setGeometry(QtCore.QRect(880, 370, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.scenario_label_4.setFont(font)
        self.scenario_label_4.setObjectName("scenario_label_4")
        self.scenario_label_5 = QtWidgets.QLabel(self.centralwidget)
        self.scenario_label_5.setGeometry(QtCore.QRect(790, 400, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.scenario_label_5.setFont(font)
        self.scenario_label_5.setObjectName("scenario_label_5")
        self.label.raise_()
        self.scenario_comboBox.raise_()
        self.scenario_label.raise_()
        self.generateButton.raise_()
        self.description_textBrowser.raise_()
        self.blueforces_comboBox.raise_()
        self.scenario_label_2.raise_()
        self.scenario_label_3.raise_()
        self.redforces_comboBox.raise_()
        self.players_spinBox.raise_()
        self.scenario_label_4.raise_()
        self.scenario_label_5.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1088, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_generateMission = QtWidgets.QAction(MainWindow)
        self.action_generateMission.setObjectName("action_generateMission")
        self.action_scenarioSelected = QtWidgets.QAction(MainWindow)
        self.action_scenarioSelected.setObjectName("action_scenarioSelected")
        self.action_blueforcesSelected = QtWidgets.QAction(MainWindow)
        self.action_blueforcesSelected.setObjectName("action_blueforcesSelected")
        self.action_redforcesSelected = QtWidgets.QAction(MainWindow)
        self.action_redforcesSelected.setObjectName("action_redforcesSelected")

        self.retranslateUi(MainWindow)
        self.generateButton.clicked.connect(self.action_generateMission.trigger)
        self.scenario_comboBox.currentIndexChanged['int'].connect(self.action_scenarioSelected.trigger)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RotorOps Mission Generator"))
        self.scenario_label.setText(_translate("MainWindow", "Battlefield:"))
        self.generateButton.setText(_translate("MainWindow", "Generate Mission"))
        self.description_textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Provide close air support for our convoys as we take back Las Vegas from the enemy!</span></p></body></html>"))
        self.scenario_label_2.setText(_translate("MainWindow", "Blue Forces:"))
        self.scenario_label_3.setText(_translate("MainWindow", "Red Forces:"))
        self.scenario_label_4.setText(_translate("MainWindow", "Players "))
        self.scenario_label_5.setText(_translate("MainWindow", "(Scales up enemy numbers)"))
        self.action_generateMission.setText(_translate("MainWindow", "_generateMission"))
        self.action_scenarioSelected.setText(_translate("MainWindow", "_scenarioSelected"))
        self.action_blueforcesSelected.setText(_translate("MainWindow", "_blueforcesSelected"))
        self.action_redforcesSelected.setText(_translate("MainWindow", "_redforcesSelected"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
