# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MissionGeneratorUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 480)
        MainWindow.setMaximumSize(QtCore.QSize(720, 480))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scenario_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.scenario_comboBox.setGeometry(QtCore.QRect(130, 30, 311, 31))
        self.scenario_comboBox.setObjectName("scenario_comboBox")
        self.scenario_label = QtWidgets.QLabel(self.centralwidget)
        self.scenario_label.setGeometry(QtCore.QRect(30, 30, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.scenario_label.setFont(font)
        self.scenario_label.setObjectName("scenario_label")
        self.generateButton = QtWidgets.QPushButton(self.centralwidget)
        self.generateButton.setGeometry(QtCore.QRect(550, 380, 141, 41))
        self.generateButton.setStyleSheet("background-color: white;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.generateButton.setObjectName("generateButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-590, 180, 1111, 501))
        self.label.setStyleSheet("border-radius: 5")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("assets/background.PNG"))
        self.label.setObjectName("label")
        self.description_textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.description_textBrowser.setGeometry(QtCore.QRect(455, 30, 251, 111))
        self.description_textBrowser.setStyleSheet("border-radius: 5px;")
        self.description_textBrowser.setObjectName("description_textBrowser")
        self.logistics_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.logistics_checkBox.setGeometry(QtCore.QRect(30, 80, 201, 21))
        self.logistics_checkBox.setObjectName("logistics_checkBox")
        self.label.raise_()
        self.scenario_comboBox.raise_()
        self.scenario_label.raise_()
        self.generateButton.raise_()
        self.description_textBrowser.raise_()
        self.logistics_checkBox.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 720, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_generateMission = QtWidgets.QAction(MainWindow)
        self.action_generateMission.setObjectName("action_generateMission")
        self.action_scenarioSelected = QtWidgets.QAction(MainWindow)
        self.action_scenarioSelected.setObjectName("action_scenarioSelected")

        self.retranslateUi(MainWindow)
        self.generateButton.clicked.connect(self.action_generateMission.trigger)
        self.scenario_comboBox.currentIndexChanged['int'].connect(self.action_scenarioSelected.trigger)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RotorOps Mission Generator"))
        self.scenario_label.setText(_translate("MainWindow", "Scenario:"))
        self.generateButton.setText(_translate("MainWindow", "Generate Mission"))
        self.description_textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Provide close air support for our convoys as we take back Las Vegas from the enemy!</p></body></html>"))
        self.logistics_checkBox.setText(_translate("MainWindow", "Smoke Active Conflict Zone"))
        self.action_generateMission.setText(_translate("MainWindow", "_generateMission"))
        self.action_scenarioSelected.setText(_translate("MainWindow", "_scenarioSelected"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
