# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'generator.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.map_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.map_comboBox.setGeometry(QtCore.QRect(170, 40, 311, 31))
        self.map_comboBox.setObjectName("map_comboBox")
        self.scenario_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.scenario_comboBox.setGeometry(QtCore.QRect(170, 90, 311, 31))
        self.scenario_comboBox.setObjectName("scenario_comboBox")
        self.map_label = QtWidgets.QLabel(self.centralwidget)
        self.map_label.setGeometry(QtCore.QRect(90, 40, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.map_label.setFont(font)
        self.map_label.setObjectName("map_label")
        self.scenario_label = QtWidgets.QLabel(self.centralwidget)
        self.scenario_label.setGeometry(QtCore.QRect(60, 90, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.scenario_label.setFont(font)
        self.scenario_label.setObjectName("scenario_label")
        self.generateButton = QtWidgets.QPushButton(self.centralwidget)
        self.generateButton.setGeometry(QtCore.QRect(470, 360, 141, 41))
        self.generateButton.setStyleSheet("background-color: white;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.generateButton.setObjectName("generateButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-100, -10, 1111, 501))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("assets/background.PNG"))
        self.label.setObjectName("label")
        self.label.raise_()
        self.map_comboBox.raise_()
        self.scenario_comboBox.raise_()
        self.map_label.raise_()
        self.scenario_label.raise_()
        self.generateButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RotorOps Mission Generator"))
        self.map_label.setText(_translate("MainWindow", "Map:"))
        self.scenario_label.setText(_translate("MainWindow", "Scenario:"))
        self.generateButton.setText(_translate("MainWindow", "Generate Mission"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
